---
- name: apply raspi-config
  become: true
  command: raspi-config --apply-os-config

- name: reboot
  become: true
  command: /sbin/shutdown -r +0 'Reboot triggered'
  async: 0
  poll: 0
  ignore_errors: true
  notify:
    - wait for reboot

- name: wait for reboot
  become: false
  local_action: wait_for host={{ inventory_hostname }} state=started delay=50 timeout=120

- name: remove default user
  become: true
  when: "raspi_config_replace_user['name'] != raspi_config_default_username"
  user: name={{raspi_config_default_username}} state=absent force=yes
  ignore_errors: true
